import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import { BackHandling } from "@/src/components/BackHandling";
import { ModalProvider } from "@/src/providers/ModalProvider";
import "./globals.css";

const pretendard = localFont({
  src: [
    {
      path: "./fonts/Pretendard-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Pretendard-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    { path: "./fonts/Pretendard-Bold.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-pretendard",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Full-screen WebView: without viewport-fit=cover, env(safe-area-inset-*) is 0.
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#1e3932",
  colorScheme: "light",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="ko" className={`${pretendard.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {/* <BackHandling> */}
        <ModalProvider>
          <div className="relative mx-auto flex min-h-dvh w-full max-w-app flex-col bg-canvas">
            {children}
          </div>
        </ModalProvider>
        {/* </BackHandling> */}
      </body>
    </html>
  );
}
